version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    # Keep scheduled version updates from creating additional branches.
    open-pull-requests-limit: 0
    groups:
      react:
        patterns: ['react', 'react-dom', '@types/react*']
      lint:
        patterns: ['eslint*', '@eslint/*', 'typescript-eslint', 'globals']
      build-and-test:
        patterns: ['vite', '@vitejs/*', 'vitest', '@vitest/*', 'typescript', '@tailwindcss/*', 'tailwindcss']

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 0
    schedule:
      interval: monthly
